#Namen in alphabetischer Reihenfolge
print("Adem Jabri ")
print("andré")
print("Arwin")
print("Bele")
print("Elía Cebrián Schwarz")
print("Rafael Fernandes Estrela")
print("Josua")
print("Adem Jabri MitNachname :)")
print("Nidhal Essghaier")
print("Rafael")
print("Arwin Semmler")
print("Bele Stieben")
print("Kerem Temel")