#Namen in alphabetischer Reihenfolge
print("Adem")
print("andré")
print("Arwin")
print("Bele")
print("Nidhal Essghaier")
print("Rafael Fernandes Estrela")
print("Adem Jabri)")
print("Josua")
print("Rafael")
print("Elía Cebrián Schwarz")
print("Arwin Semmler")
print("Bele Stieben")
print("Kerem Temel")